// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using Xenko.Rendering;

namespace FogOfWarDirectional
{
    public static partial class FogOfWarDirectionalShaderKeys
    {
        public static readonly ValueParameterKey<float> FogOpacity = ParameterKeys.NewValue<float>(.775f);
    }
}
